USE `mydb`;

CREATE TABLE `user` (
    `ID` INT(8) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `BALANCE` FLOAT,
    `AGE` INT(3),
    `PHOTO` VARCHAR(255),
    `IS_ADMIN` ENUM('0', '1') NOT NULL,
    `IS_EMPLOYEE` ENUM('0', '') NOT NULL,
    `CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_LOGIN` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

INSERT INTO `users`(ID, NAME, EMAIL, BALANCE, AGE, IS_EMPLOYEE, IS_ADMIN, CREATE_DATE) VALUES(1, 'user1', 'user1@gmail.com', 0.0, 20, '0' , '1', '2023-07-06 10:45:10');
INSERT INTO `users`(ID, NAME, EMAIL, BALANCE, AGE, IS_EMPLOYEE, IS_ADMIN, CREATE_DATE) VALUES(2, 'user2', 'user2@gmail.com', 100.1, 30, '0' , '0', '2023-07-06 10:45:10');
INSERT INTO `users`(ID, NAME, EMAIL, BALANCE, AGE, IS_EMPLOYEE, IS_ADMIN, CREATE_DATE) VALUES(3, 'user3', 'user2@gmail.com', 500.2, 40, '1', '0', '2023-07-06 10:45:10');