USE 'mydb';

CREATE TABLE `car` (
    `ID` INT(8) NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NOT NULL,
    `PRICE` FLOAT NOT NULL,
    `TYPE` VARCHAR(30) NOT NULL,
    `MODEL` VARCHAR(255) NOT NULL,
    `PHOTO` VARCHAR(255),
    `EMPLOYEE_ID` INT NOT NULL,
    `IS_PUBLISHED` ENUM('0', '1') NOT NULL,
    `CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`), FOREIGN KEY (EMPLOYEE)  REFERENCES users (Id)
);

INSERT INTO `car`(ID, TITLE, DESCRIPTION, PRICE, TYPE, MODEL, EMPLOYEE, IS_PUBLISHED, CREATE_DATE) VALUES(1, 'CAR1', 'DESCRTIPTION1', 1000, 'electro', 'bmw', 3, '0', '2023-07-06 10:45:10');
INSERT INTO `car`(ID, TITLE, DESCRIPTION, PRICE, TYPE, MODEL, EMPLOYEE, IS_PUBLISHED, CREATE_DATE) VALUES(2, 'CAR2', 'DESCRTIPTION2', 10000, 'gasoline', 'audi', 3, '1', '2023-07-06 10:45:10');
INSERT INTO `car`(ID, TITLE, DESCRIPTION, PRICE, TYPE, MODEL, EMPLOYEE, IS_PUBLISHED, CREATE_DATE) VALUES(3, 'CAR3', 'DESCRTIPTION3', 50000, 'diesel', 'bmw', 3, '0', '2023-07-06 10:45:10');